#!/bin/bash
#
# Weekly Dashboard Auto-Update Script
# Fetches latest ad platform data and updates the dashboard
#
# Usage: ./weekly-update.sh [WEEK_ENDING_DATE]
# Example: ./weekly-update.sh 2025-11-02
#
# If no date provided, uses last Saturday

set -e

# Get week ending date (default to last Saturday)
if [ -z "$1" ]; then
    # Calculate last Saturday
    WEEK_ENDING=$(date -v-saturday +%Y-%m-%d 2>/dev/null || date -d "last saturday" +%Y-%m-%d)
else
    WEEK_ENDING=$1
fi

WEEK_LABEL=$(date -j -f "%Y-%m-%d" "$WEEK_ENDING" "+%-m/%-d" 2>/dev/null || date -d "$WEEK_ENDING" "+%-m/%-d")

echo "================================"
echo "WEEKLY DASHBOARD UPDATE"
echo "Week Ending: $WEEK_ENDING ($WEEK_LABEL)"
echo "================================"
echo ""

# Navigate to dashboard directory
cd "$(dirname "$0")"

# Pull latest changes
echo "📥 Pulling latest changes from GitHub..."
git pull origin main

# Run update script
echo ""
echo "🔄 Fetching ad platform data and updating dashboard..."
python3 update-dashboard.py

# Check for changes
if git diff --quiet app.js; then
    echo ""
    echo "ℹ️  No changes detected - data already up to date"
    exit 0
fi

# Show changes
echo ""
echo "📊 Changes to be committed:"
git diff --stat app.js

# Commit and push
echo ""
read -p "✅ Commit and push these changes? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    git add app.js update-dashboard.py
    git commit -m "data: update dashboard for week ending $WEEK_LABEL

- Updated totals with real Google Ads API data
- Microsoft/Reddit/LinkedIn using previous week (API integration pending)
- Auto-generated by weekly-update.sh"
    
    git push origin main
    
    echo ""
    echo "✅ Dashboard updated and deployed!"
    echo "🌐 View at: https://your-vercel-url.vercel.app"
else
    echo ""
    echo "❌ Update cancelled"
    exit 1
fi
